site_name: Omics-analysis
repo_url: https://github.com/jinghuazhao/Omics-analysis
edit_uri: ""
nav:
  - "": README.md
  - resources.md
  - Cases:
    - AF/README.md
    - BMI/README.md
    - CAD/README.md
    - T2D/README.md
  - Genomics: genomics.md
  - Proteomics: proteomics.md
theme:
    name: mkdocs
    nav_style: dark
    highlightjs: true
    hljs_languages:
        - Bash
        - HTML
        - Java
        - JavaScript
        - Perl
        - Python
        - R
        - rust
        - yaml
extra_css:
    - stylesheets/extra.css
plugins:
    - search
    - mermaid2
markdown_extensions:
  - attr_list
  - footnotes
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - codehilite

validation:
  unrecognized_links: ignore
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
